#!/usr/bin/env python3

import tkinter
import os

def irsend():
    statustxt = "\nStatus: Transmitting"
    status.configure(text = statustxt)
    window.update()
    cmd=f"echo {txtinput.get()} | ir-sender"
    os.system(cmd)
    txtinput.delete(0, 'end')
    statustxt = "\nStatus: Completed."
    status.configure(text = statustxt)

#set up form
window = tkinter.Tk()
window.title("IR Sender")
window.geometry('350x200')

#input elem
lable = tkinter.Label(window, text="Text: ")
lable.grid(column=0, row=0)
txtinput = tkinter.Entry(window, width=10)
txtinput.grid(column=1, row=0)
button = tkinter.Button(window, text="Send via IR", command=irsend)
button.grid(column=2, row=0)
status=tkinter.Label(window, text="\nStatus: ready for input",justify="left")
status.grid(columnspan=3, row=1)
about=tkinter.Label(window, text="\nThis tool will send a message via infrared to the RP2040 on the other side of the air gap.", wraplength=180, fg = "grey",justify="left")
about.grid(columnspan=3, row=2)

if __name__=="__main__":
  window.mainloop()


